import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import StoreProvider from "@/store/StoreProvider"
// import { ThemeProvider } from "@/components/providers/ThemeProvider"
import SessionProvider from "@/components/providers/SessionProvider"
import Header from "@/components/Header"
import { Toaster } from "@/components/ui/toaster"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s",
    default: "Rewind"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <StoreProvider>
            <Header />
            {children}
            <Toaster />
          </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
