import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from "antd"
import StoreProvider from "@/store/StoreProvider";
import SessionProvider from "@/components/providers/SessionProvider"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s",
    default: "Rewind"
  },
  description: "Generated by create next app",
};

// const darkTheme = {
//   token: {
//     colorPrimary: '#1890ff',
//     colorBgBase: '#141414',
//     colorTextBase: '#ffffff',
//     colorBorder: '#444',
//   },
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConfigProvider>
          <AntdRegistry>
            <SessionProvider>
              <StoreProvider>
                {children}
              </StoreProvider>
            </SessionProvider>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
